export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const AUTH_LOGOUT_START = 'AUTH_LOGOUT_START';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const COUNTRY_SUCCESS = 'COUNTRY_SUCCESS';
export const CITY_SUCCESS = 'CITY_SUCCESS';
export const CREATEUSER_SUCCESS = 'CREATEUSER_SUCCESS';
export const CREATEUSER_FAIL = 'CREATEUSER_FAIL';
export const SET_EXIST_USER_STATUS = 'SET_EXIST_USER_STATUS';

export const APPOINTMENTLIST_SUCCESS = 'APPOINTMENTLIST_SUCCESS';
export const SET_APPOINTMENTDATE = 'SET_APPOINTMENTDATE';
export const SET_APPOINTMENTDATA = 'SET_APPOINTMENTDATA';
export const APPOINTMENTTYPE_SUCCESS = 'APPOINTMENTTYPE_SUCCESS';
export const GET_APPOINTMENT_DATA = 'GET_APPOINTMENT_DATA';

export const PHYSICIANLIST_SUCCESS = 'PHYSICIANLIST_SUCCESS';
export const SET_PHY_FILTER_TEXT = 'SET_PHY_FILTER_TEXT';
export const SET_SELECTED_PHY_ID = 'SET_SELECTED_PHY_ID';

export const GET_USERDETAIL_SUCCESS = 'GET_USERDETAIL_SUCCESS';
export const UPDATE_USERDETAILS_SUCCESS = 'UPDATE_USERDETAILS_SUCCESS';
export const UPDATE_USERDETAILS_FAILURE = 'UPDATE_USERDETAILS_FAILURE';

export const GET_SLOTS_SUCCESS = 'GET_SLOTS_SUCCESS';
export const GET_APPOINTMENT_COST_DETAILS_SUCCESS = 'GET_APPOINTMENT_COST_DETAILS_SUCCESS';
export const RPAY_ORDER_ID_SUCCESS = 'RPAY_ORDER_ID_SUCCESS';

// export const API_URL = 'https://www.conferadmin.com/restapi';
export const API_URL = 'https://www.skrepository.com/restapi/';